from pathlib import Path
import sqlite3
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

REPO_ROOT = Path(__file__).resolve().parents[1]
STATS_DB = REPO_ROOT / "data" / "oddlua_stats.sqlite"
SERVER_WS = REPO_ROOT.parent / "server" / "scripts" / "actions" / "weaponskills"

from oddlua.weaponskills import (
    WeaponSkillEligibilityContext,
    display_name_for_weaponskill,
    eligible_weaponskills_for_job,
    job_level_from_jobs_hex,
    load_weaponskill_catalog,
    normalize_weaponskill_key,
    set_name_for_weaponskill,
)
from oddlua.weaponskill_scripts import parse_weaponskill_script
from oddlua.itemstats import ItemStatsIndex, load_item_stats_from_db


def test_loads_all_catseye_enabled_weaponskills_from_stats_db() -> None:
    with sqlite3.connect(STATS_DB) as db:
        expected_count = db.execute("select count(*) from weapon_skills").fetchone()[0]

    catalog = load_weaponskill_catalog(STATS_DB)

    assert len(catalog) == expected_count
    assert catalog["tachi_gekko"].weapon_family == "great_katana"
    assert catalog["tachi_gekko"].display_name == "Tachi: Gekko"
    assert catalog["savage_blade"].weapon_family == "sword"
    assert catalog["hexa_strike"].weapon_family == "club"
    assert catalog["leaden_salute"].element_name == "Dark"


def test_catalog_maps_catseye_weapon_skill_element_ids() -> None:
    catalog = load_weaponskill_catalog(STATS_DB)

    assert catalog["frostbite"].element_name == "Ice"
    assert catalog["earth_crusher"].element_name == "Earth"
    assert catalog["blade_teki"].element_name == "Water"
    assert catalog["trueflight"].element_name == "Light"
    assert catalog["leaden_salute"].element_name == "Dark"


def test_jobs_hex_decodes_job_specific_weapon_skill_levels() -> None:
    catalog = load_weaponskill_catalog(STATS_DB)

    assert job_level_from_jobs_hex(catalog["tachi_gekko"].jobs_hex, "SAM") == 1
    assert job_level_from_jobs_hex(catalog["tachi_gekko"].jobs_hex, "WAR") == 0
    assert job_level_from_jobs_hex(catalog["savage_blade"].jobs_hex, "RDM") > 0


def _eligibility_context(index: ItemStatsIndex, job: str, level: int) -> WeaponSkillEligibilityContext:
    return WeaponSkillEligibilityContext(
        job=job,
        character_level=level,
        skill_caps_by_level_rank=index.skill_caps_by_level_rank,
        skill_ranks_by_skill_job=index.skill_ranks_by_skill_job,
        learned_unlock_ids=frozenset(),
    )


def test_eligible_weaponskills_for_sam_use_skill_caps_instead_of_jobs_byte_level() -> None:
    catalog = load_weaponskill_catalog(STATS_DB)
    index = load_item_stats_from_db(STATS_DB)

    sam_31 = {
        ws.key
        for ws in eligible_weaponskills_for_job(
            catalog,
            _eligibility_context(index, "SAM", 31),
        )
    }
    sam_65 = {
        ws.key
        for ws in eligible_weaponskills_for_job(
            catalog,
            _eligibility_context(index, "SAM", 65),
        )
    }
    sam_75 = {
        ws.key
        for ws in eligible_weaponskills_for_job(
            catalog,
            _eligibility_context(index, "SAM", 75),
        )
    }

    assert "tachi_hobaku" in sam_31
    assert "tachi_gekko" not in sam_31
    assert "tachi_gekko" in sam_65
    assert "tachi_shoha" not in sam_75
    assert "savage_blade" not in sam_75


def test_unlock_only_zero_job_rows_are_cataloged_but_not_autogenerated() -> None:
    catalog = load_weaponskill_catalog(STATS_DB)
    index = load_item_stats_from_db(STATS_DB)
    eligible = eligible_weaponskills_for_job(
        catalog,
        _eligibility_context(index, "SAM", 75),
    )
    keys = {ws.key for ws in eligible}

    assert "tachi_kaiten" in catalog
    assert "tachi_kaiten" not in keys


def test_weaponskill_names_normalize_to_stable_lua_set_names() -> None:
    assert normalize_weaponskill_key("Tachi: Gekko") == "tachi_gekko"
    assert normalize_weaponskill_key("tachi_gekko") == "tachi_gekko"
    assert normalize_weaponskill_key("Savage Blade") == "savage_blade"
    assert display_name_for_weaponskill("blade_jin") == "Blade: Jin"
    assert set_name_for_weaponskill("Tachi: Gekko") == "WS_Tachi_Gekko"


def test_parse_physical_weaponskill_script_uses_adoulin_branch() -> None:
    parsed = parse_weaponskill_script(
        SERVER_WS / "tachi_gekko.lua",
        use_adoulin_changes=True,
    )

    assert parsed.damage_kind == "physical"
    assert parsed.num_hits == 1
    assert parsed.wsc == {"STR": 0.75}
    assert parsed.ftp_mod == (1.5625, 2.6875, 4.125)
    assert parsed.attack_multiplier == (2.0, 2.0, 2.0)
    assert parsed.additional_effects == ("silence",)
    assert parsed.parser_warnings == ()


def test_parse_magical_weaponskill_script_detects_element_and_mab() -> None:
    parsed = parse_weaponskill_script(
        SERVER_WS / "sanguine_blade.lua",
        use_adoulin_changes=True,
    )

    assert parsed.damage_kind == "magical"
    assert parsed.element_name == "Dark"
    assert parsed.includes_mab is True
    assert parsed.wsc == {"STR": 0.3, "MND": 0.5}
    assert parsed.parser_warnings == ()


def test_parse_multihit_crit_weaponskill_script_detects_crit_profile() -> None:
    parsed = parse_weaponskill_script(
        SERVER_WS / "hexa_strike.lua",
        use_adoulin_changes=True,
    )

    assert parsed.damage_kind == "physical"
    assert parsed.num_hits == 6
    assert parsed.crit_varies == (0.1, 0.3, 0.5)
    assert parsed.wsc == {"STR": 0.3, "MND": 0.3}
    assert parsed.parser_warnings == ()


def test_parse_merit_weaponskill_wsc_expressions_use_full_merit_value() -> None:
    cases = {
        "stardiver": {"STR": 0.85},
        "shijin_spiral": {"DEX": 0.85},
        "tachi_shoha": {"STR": 0.85},
        "apex_arrow": {"AGI": 0.85},
        "requiescat": {"MND": 0.85},
    }

    for script_name, expected in cases.items():
        parsed = parse_weaponskill_script(
            SERVER_WS / f"{script_name}.lua",
            use_adoulin_changes=True,
        )
        assert parsed.wsc == expected
        assert parsed.parser_warnings == ()


def test_parse_weaponskill_script_warns_and_skips_unterminated_adoulin_block(
    tmp_path: Path,
) -> None:
    script = tmp_path / "unterminated.lua"
    script.write_text(
        """
        local weaponskillObject = {}
        local params = {}
        params.numHits = 2

        if xi.settings.main.USE_ADOULIN_WEAPON_SKILL_CHANGES then
            params.ftpMod = { 1, 2, 3 }
        """
    )

    parsed = parse_weaponskill_script(script, use_adoulin_changes=True)

    assert parsed.num_hits == 2
    assert parsed.ftp_mod == (1.0, 1.0, 1.0)
    assert any(
        "Unterminated USE_ADOULIN_WEAPON_SKILL_CHANGES block" in warning
        for warning in parsed.parser_warnings
    )


def test_collect_assignments_ignores_params_in_string_literals(tmp_path: Path) -> None:
    script = tmp_path / "string_literal_assignments.lua"
    script.write_text(
        """
        local note = "params.numHits = 99"
        local note2 = 'params.ftpMod = { 9, 9, 9 }'
        local params = {}
        params.numHits = 2
        """,
        encoding="utf-8",
    )

    parsed = parse_weaponskill_script(script, use_adoulin_changes=False)

    assert parsed.num_hits == 2
    assert parsed.ftp_mod == (1.0, 1.0, 1.0)
    assert parsed.parser_warnings == ()
