JOB_ID_BY_ABBR = {
    "WAR": 1,
    "MNK": 2,
    "WHM": 3,
    "BLM": 4,
    "RDM": 5,
    "THF": 6,
    "PLD": 7,
    "DRK": 8,
    "BST": 9,
    "BRD": 10,
    "RNG": 11,
    "SAM": 12,
    "NIN": 13,
    "DRG": 14,
    "SMN": 15,
    "BLU": 16,
    "COR": 17,
    "PUP": 18,
    "DNC": 19,
    "SCH": 20,
    "GEO": 21,
    "RUN": 22,
}

WEAPON_FAMILY_BY_SKILL = {
    1: "hand_to_hand",
    2: "dagger",
    3: "sword",
    4: "great_sword",
    5: "axe",
    6: "great_axe",
    7: "scythe",
    8: "polearm",
    9: "katana",
    10: "great_katana",
    11: "club",
    12: "staff",
    25: "bow",
    26: "gun",
    27: "throwing",
    40: "instrument",
    41: "instrument",
    42: "instrument",
    45: "instrument",
}
